package actions

import (
	"github.com/cdacontrol/cda/models"
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Device)
// DB Table: Plural (devices)
// Resource: Plural (Devices)
// Path: Plural (/devices)
// View Template Folder: Plural (/templates/devices/)

// DevicesResource is the resource for the Device model
type DevicesResource struct {
	buffalo.Resource
}

// List gets all Devices. This function is mapped to the path
// GET /devices
func (v DevicesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	devices := &models.Devices{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Devices from the DB
	if err := q.All(devices); err != nil {
		return errors.WithStack(err)
	}

	// Make Devices available inside the html template
	c.Set("devices", devices)

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.HTML("devices/index.html"))
}

// Show gets the data for one Device. This function is mapped to
// the path GET /devices/{device_id}
func (v DevicesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty Device
	device := &models.Device{}

	// To find the Device the parameter device_id is used.
	if err := tx.Find(device, c.Param("device_id")); err != nil {
		return c.Error(404, err)
	}

	// Make device available inside the html template
	c.Set("device", device)

	return c.Render(200, r.HTML("devices/show.html"))
}

// New renders the form for creating a new Device.
// This function is mapped to the path GET /devices/new
func (v DevicesResource) New(c buffalo.Context) error {
	// Make device available inside the html template
	c.Set("device", &models.Device{})

	return c.Render(200, r.HTML("devices/new.html"))
}

// Create adds a Device to the DB. This function is mapped to the
// path POST /devices
func (v DevicesResource) Create(c buffalo.Context) error {
	// Allocate an empty Device
	device := &models.Device{}

	// Bind device to the html form elements
	if err := c.Bind(device); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(device)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make device available inside the html template
		c.Set("device", device)

		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("devices/new.html"))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Device was created successfully")

	// and redirect to the devices index page
	return c.Redirect(302, "/devices/%s", device.ID)
}

// Edit renders a edit form for a Device. This function is
// mapped to the path GET /devices/{device_id}/edit
func (v DevicesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty Device
	device := &models.Device{}

	if err := tx.Find(device, c.Param("device_id")); err != nil {
		return c.Error(404, err)
	}

	// Make device available inside the html template
	c.Set("device", device)
	return c.Render(200, r.HTML("devices/edit.html"))
}

// Update changes a Device in the DB. This function is mapped to
// the path PUT /devices/{device_id}
func (v DevicesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty Device
	device := &models.Device{}

	if err := tx.Find(device, c.Param("device_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Device to the html form elements
	if err := c.Bind(device); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(device)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make device available inside the html template
		c.Set("device", device)

		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("devices/edit.html"))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Device was updated successfully")

	// and redirect to the devices index page
	return c.Redirect(302, "/devices/%s", device.ID)
}

// Destroy deletes a Device from the DB. This function is mapped
// to the path DELETE /devices/{device_id}
func (v DevicesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty Device
	device := &models.Device{}

	// To find the Device the parameter device_id is used.
	if err := tx.Find(device, c.Param("device_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(device); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Device was destroyed successfully")

	// Redirect to the devices index page
	return c.Redirect(302, "/devices")
}
